### ISSUE TITLE
Is this on the Discord?

### ISSUE THREAD

**Issue by slowpoke111** [nikoniko78/scripts-java-physion#2]
Have you posted the link on the Discord yet?

**Comment by nikoniko78** [comment]
No, I do not currently have access to Discord. It would be a great help if you could post the link yourself and explain the reasoning. Thank you for your contributions and active use.

**Comment by slowpoke111** [comment]
I will post the link soon. How do you want to be credited as the creator?

**Comment by nikoniko78** [comment]
It would be simple and easy if you just stated that you were not the creator of the repository, and that I was not able to use discord at the moment. Thank you!
