### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by slowpoke111** [nikoniko78/scripts-java-physion#3]
A license clearly states that this code is open source and that it s provided free of warranty or liability to the author.

To create one, add a new file titled LICENSE, and it will let you choose one. I would recommend MIT

**Comment by nikoniko78** [comment]
As this is simply a place to view and easily access scripts, a license is not required. Thank you for the reccomendation!

**Comment by nikoniko78** [comment]
Is the Unlicense a good option for public code without copyright?

**Comment by slowpoke111** [comment]
I would use the MIT or CC0 (Creative Commons Zero) instead of the Unilicense. CC0 is essentially public domain and also mentions that software is provided "as-is" without any guarantee of it working and no liability for the creator. The Unilicense is informal and vague, so it can be interpreted differentially by different people. MIT and CC0 are much clearer. If you want the code in the public domain use CC0. If you want some control over the code use the MIT.
