### ISSUE TITLE
Script attribution issues

### ISSUE THREAD

**Issue by Carstyle476** [nikoniko78/scripts-java-physion#36]
I was the original writer of Bomb.js, but no-one noticed my original "bomb" scene before I deleted it.
And yes, I do remember writing it very clearly. I apologize if I seem aggressive, I'm just saying it's actually mine. Thanks!

**Comment by Carstyle476** [comment]
Issue no. 2 is that Duplicator.js is marked as "unknown scene and creator", when in fact I wrote that and it's in the scene "Coin Game" by Sirfryingpan. Again, apologize for any aggressiveness. I'm just saying. Thanks!

**Comment by nikoniko78** [comment]
Thank you for the clarification. I will fix this as soon as possible. Sorry!

**Comment by Carstyle476** [comment]
No problem

**Comment by nikoniko78** [comment]
Your issue has been resolved. Please feel free to report anything that is incorrect or needs to be fixed.

**Comment by Carstyle476** [comment]
Wait! Before you close this issue, I noticed one more thing: Start.js is actually ControlIJKL, found in my "Maze", and End.js is actually Enemy, also found in my "Maze". The real pathfinder script is in "Pathfinding!"
(aw, I was too slow, anyways thx for fixing the previous issues)

**Comment by nikoniko78** [comment]
It's fine. I knew this beforehand, I just named it to start and end for clarification.

**Comment by Carstyle476** [comment]
Ohhhh alright sorry

**Comment by nikoniko78** [comment]
I also replied to your email

**Comment by Carstyle476** [comment]
email? what email?

**Comment by Carstyle476** [comment]
i never sent you anything via gmail! the guy is a scammer! don't trust him!

**Comment by nikoniko78** [comment]
Sorry, I've got two people I am managing. Thought you were someone else... Sorry!
